import { Injectable } from '@angular/core';
import {CountryModel} from '../models/country.model';

@Injectable({
  providedIn: 'root'
})
export class CountryService {
  country: CountryModel[] = [
    {countryName: 'Afghanistan', countryCode: 'AFG', flag: 'Afghanistan.png'},
    {countryName: 'Albania', countryCode: 'ALB', flag: 'Albania.png'},
    {countryName: 'Algeria', countryCode: 'DZA', flag: 'Algeria.png'},
    {countryName: 'American Samoa', countryCode: 'ASM', flag: 'American Samoa.png'},
    {countryName: 'Andorra', countryCode: 'AND', flag: 'Andorra.png'},
    {countryName: 'Angola', countryCode: 'AGO', flag: 'Angola.png'},
    {countryName: 'Anguilla', countryCode: 'AIA', flag: 'Anguilla.png'},
    {countryName: 'Antarctica', countryCode: 'ATA', flag: 'Antarctica.png'},
    {countryName: 'Antigua and Barbuda', countryCode: 'ATG', flag: 'Antigua&Barbuda.png'},
    {countryName: 'Argentina', countryCode: 'ARG', flag: 'Argentina.png'},
    {countryName: 'Armenia', countryCode: 'ARM', flag: 'Armenia.png'},
    {countryName: 'Aruba', countryCode: 'ABW', flag: 'Aruba.png'},
    {countryName: 'Australia', countryCode: 'AUS', flag: 'Australia.png'},
    {countryName: 'Austria', countryCode: 'AUT', flag: 'Austria.png'},
    {countryName: 'Azerbaijan', countryCode: 'AZE', flag: 'Azerbaijan.png'},
    {countryName: 'Bahamas ', countryCode: 'BHS', flag: 'Bahamas.png'},
    {countryName: 'Bahrain', countryCode: 'BHR', flag: 'Bahrain.png'},
    {countryName: 'Bangladesh', countryCode: 'BGD', flag: 'Bangladesh.png'},
    {countryName: 'Barbados', countryCode: 'BRB', flag: 'Barbados.png'},
    {countryName: 'Belarus', countryCode: 'BLR', flag: 'Belarus.png'},
    {countryName: 'Belgium', countryCode: 'BEL', flag: 'Belgium.png'},
    {countryName: 'Belize', countryCode: 'BLZ', flag: 'Belize.png'},
    {countryName: 'Benin', countryCode: 'BEN', flag: 'Benin.png'},
    {countryName: 'Bermuda', countryCode: 'BMU', flag: 'Bermuda.png'},
    {countryName: 'Bhutan', countryCode: 'BTN', flag: 'Bhutan.png'},
    {countryName: 'Bolivia', countryCode: 'BOL', flag: 'Bolivia.png'},
    {countryName: 'Bonaire, Sint Eustatius and Saba', countryCode: 'BES', flag: 'Netherlands.png'},
    {countryName: 'Bosnia and Herzegovina(Plurinational State of)', countryCode: 'BIH', flag: 'BosniaHerzegovina.png'},
    {countryName: 'Botswana', countryCode: 'BWA', flag: 'Botswana.png'},
    {countryName: 'Bouvet Island', countryCode: 'BVT', flag: 'Norway.png'},
    {countryName: 'Brazil', countryCode: 'BRA', flag: 'Brazil.png'},
    {countryName: 'British Indian Ocean Territory', countryCode: 'IOT', flag: 'BritishIndianOceanTerritory.png'},
    {countryName: 'Brunei Darussalam', countryCode: 'BRN', flag: 'Brunei.png'},
    {countryName: 'Bulgaria', countryCode: 'BGR', flag: 'Bulgaria.png'},
    {countryName: 'Burkina Faso', countryCode: 'BFA', flag: 'Burkinafaso.png'},
    {countryName: 'Burundi', countryCode: 'BDI', flag: 'Burundi.png'},
    {countryName: 'Cabo Verde', countryCode: 'CPV', flag: 'Caboverde.png'},
    {countryName: 'Cambodia', countryCode: 'KHM', flag: 'Cambodja.png'},
    {countryName: 'Cameroon', countryCode: 'CMR', flag: 'Cameroon.png'},
    {countryName: 'Canada', countryCode: 'CAN', flag: 'Canada.png'},
    {countryName: 'Cayman Islands ', countryCode: 'CYM', flag: 'CaymanIslands.png'},
    {countryName: 'Central African Republic ', countryCode: 'CAF', flag: 'CentralAfricanRepublic.png'},
    {countryName: 'Chad', countryCode: 'TCD', flag: 'Chad.png'},
    {countryName: 'Chile', countryCode: 'CHL', flag: 'Chile.png'},
    {countryName: 'China', countryCode: 'CHN', flag: 'China.png'},
    {countryName: 'Christmas Island', countryCode: 'CXR', flag: 'Christmasisland.png'},
    {countryName: 'Cocos Island', countryCode: 'CCK', flag: 'CocosIsland.png'},
    {countryName: 'Colombia', countryCode: 'COL', flag: 'Colombia.png'},
    {countryName: 'Comoros ', countryCode: 'COM', flag: 'Comoros.png'},
    {countryName: 'The Democratic Republic of the Congo', countryCode: 'COD', flag: 'Congo-Kinshasa(Zaire).png'},
    {countryName: 'Cook Islands', countryCode: 'COK', flag: 'CookIslands.png'},
    {countryName: 'Costa Rica', countryCode: 'CRI', flag: 'CostaRica.png'},
    {countryName: 'Croatia', countryCode: 'HRV', flag: 'Croatia.png'},
    {countryName: 'Cuba', countryCode: 'CUB', flag: 'Cuba.png'},
    {countryName: 'Curaçao', countryCode: 'CUW', flag: 'Curacao.png'},
    {countryName: 'Cyprus', countryCode: 'CYP', flag: 'Cyprus.png'},
    {countryName: 'Czechia', countryCode: 'CZE', flag: 'CzechRepublic.png'},
    {countryName: "Côte d'Ivoire", countryCode: 'CIV', flag: "Ivoirecoast.png"},
    {countryName: 'Denmark', countryCode: 'DNK', flag: 'Denmark.png'},
    {countryName: 'Djibouti', countryCode: 'DJI', flag: 'Djibouti.png'},
    {countryName: 'Dominica', countryCode: 'DMA', flag: 'Dominica.png'},
    {countryName: 'Dominican Republic ', countryCode: 'DOM', flag: 'Dominican Republic.png'},
    {countryName: 'Ecuador', countryCode: 'ECU', flag: 'Ecuador.png'},
    {countryName: 'Egypt', countryCode: 'EGY', flag: 'Egypt.png'},
    {countryName: 'El Salvador', countryCode: 'SLV', flag: 'ElSalvador.png'},
    {countryName: 'Equatorial Guinea', countryCode: 'GNQ', flag: 'EquatorialGuinea.png'},
    {countryName: 'Eritrea', countryCode: 'ERI', flag: 'Eritrea.png'},
    {countryName: 'Estonia', countryCode: 'EST', flag: 'Estonia.png'},
    {countryName: 'Eswatini', countryCode: 'SWZ', flag: 'Eswatini.png'},
    {countryName: 'Ethiopia	', countryCode: 'ETH', flag: 'Ethiopia.png'},
    {countryName: 'Falkland Islands', countryCode: 'FLK', flag: 'Falklandislands.png'},
    {countryName: 'Faroe Islands ', countryCode: 'FRO', flag: 'Faroes.png'},
    {countryName: 'Fiji', countryCode: 'FJI', flag: 'Fiji.png'},
    {countryName: 'Finland', countryCode: 'FIN', flag: 'Finland.png'},
    {countryName: 'France', countryCode: 'FRA', flag: 'France.png'},
    {countryName: 'Gabon', countryCode: 'GAB', flag: 'Gabon.png'},
    {countryName: 'Gambia', countryCode: 'GMB', flag: 'Gambia.png'},
    {countryName: 'Georgia', countryCode: 'GEO', flag: 'Georgia.png'},
    {countryName: 'Germany', countryCode: 'DEU', flag: 'Germany.png'},
    {countryName: 'Ghana', countryCode: 'GHA', flag: 'Ghana.png'},
    {countryName: 'Gibraltar', countryCode: 'GIB', flag: 'Gibraltar.png'},
    {countryName: 'Greece', countryCode: 'GRC', flag: 'Greece.png'},
    {countryName: 'Greenland', countryCode: 'GRL', flag: 'Greenland.png'},
    {countryName: 'Grenada', countryCode: 'GRD', flag: 'Grenada.png'},
    {countryName: 'Guadeloupe', countryCode: 'GLP', flag: 'Guadeloupe.png'},
    {countryName: 'Guam', countryCode: 'GUM', flag: 'Guam.png'},
    {countryName: 'Guatemala', countryCode: 'GTM', flag: 'Guatemala.png'},
    {countryName: 'Guernsey	', countryCode: 'GGY', flag: 'Guernsey.png'},
    {countryName: 'Guinea', countryCode: 'GIN', flag: 'Guinea.png'},
    {countryName: 'Guinea-Bissau', countryCode: 'GNB', flag: 'GuineaBissau.png'},
    {countryName: 'Guyana', countryCode: 'GUY', flag: 'Guyana.png'},
    {countryName: 'Haiti', countryCode: 'HTI', flag: 'Haiti.png'},
    {countryName: 'Heard Island and McDonald Islands', countryCode: 'HMD', flag: 'Australia.png'},
    {countryName: 'Holy See', countryCode: 'VAT', flag: 'Holysee.png'},
    {countryName: 'Honduras', countryCode: 'HND', flag: 'Honduras.png'},
    {countryName: 'Hong Kong', countryCode: 'HKG', flag: 'HongKong.png'},
    {countryName: 'Hungary', countryCode: 'HUN', flag: 'Hungary.png'},
    {countryName: 'Iceland', countryCode: 'ISL', flag: 'Iceland.png'},
    {countryName: 'India', countryCode: 'IND', flag: 'India.png'},
    {countryName: 'Indonesia', countryCode: 'IDN', flag: 'Indonezia.png'},
    {countryName: 'Iran (Islamic Republic of)', countryCode: 'IRN', flag: 'Iran.png'},
    {countryName: 'Iraq', countryCode: 'IRQ', flag: 'Iraq.png'},
    {countryName: 'Ireland', countryCode: 'IRL', flag: 'Ireland.png'},
    {countryName: 'Isle of Man', countryCode: 'IMN', flag: 'IsleofMan.png'},
    {countryName: 'Israel', countryCode: 'ISR', flag: 'Israel.png'},
    {countryName: 'Italy', countryCode: 'ITA', flag: 'Italy.png'},
    {countryName: 'Jamaica', countryCode: 'JAM', flag: 'Jamaica.png'},
    {countryName: 'Japan', countryCode: 'JPN', flag: 'Japan.png'},
    {countryName: 'Jersey', countryCode: 'JEY', flag: 'Jersey.png'},
    {countryName: 'Jordan', countryCode: 'JOR', flag: 'Jordan.png'},
    {countryName: 'Kazakhstan', countryCode: 'KAZ', flag: 'Kazakhstan.png'},
    {countryName: 'Kenya', countryCode: 'KEN', flag: 'Kenya.png'},
    {countryName: 'Kiribati', countryCode: 'KIR', flag: 'Kiribati.png'},
    {countryName: 'North Korea (the Democratic People\'s Republic of)', countryCode: 'PRK', flag: 'NorthKorea.png'},
    {countryName: 'Kuwait', countryCode: 'KWT', flag: 'Kuwait.png'},
    {countryName: 'Kyrgyzstan', countryCode: 'KGZ', flag: 'Kyrgyzstan.png'},
    {countryName: 'Laos', countryCode: 'LAO', flag: 'Laos.png'},
    {countryName: 'Latvia', countryCode: 'LVA', flag: 'Latvia.png'},
    {countryName: 'Lebanon', countryCode: 'LBN', flag: 'Lebanon.png'},
    {countryName: 'Lesotho', countryCode: 'LSO', flag: 'Lesotho.png'},
    {countryName: 'Liberia', countryCode: 'LBR', flag: 'Liberia.png'},
    {countryName: 'Libya', countryCode: 'LBY', flag: 'Libya.png'},
    {countryName: 'Liechtenstein', countryCode: 'LIE', flag: 'Liechtenshein.png'},
    {countryName: 'Lithuania', countryCode: 'LTU', flag: 'Lithuania.png'},
    {countryName: 'Luxembourg', countryCode: 'LUX', flag: 'Luxembourg.png'},
    {countryName: 'Macao', countryCode: 'MAC', flag: 'Macao.png'},
    {countryName: 'Madagascar', countryCode: 'MDG', flag: 'Madagascar.png'},
    {countryName: 'Malawi', countryCode: 'MWI', flag: 'Malawi.png'},
    {countryName: 'Malaysia', countryCode: 'MYS	', flag: 'Malaysia.png'},
    {countryName: 'Maldives', countryCode: 'MDV	', flag: 'Maldives.png'},
    {countryName: 'Mali', countryCode: 'MLI	', flag: 'Mali.png'},
    {countryName: 'Malta', countryCode: 'MLT', flag: 'Malta.png'},
    {countryName: 'Marshall Islands ', countryCode: 'MHL', flag: 'MarshallIslands.png'},
    {countryName: 'Martinique', countryCode: 'MTQ', flag: 'Martinique.png'},
    {countryName: 'Mauritania', countryCode: 'MRT', flag: 'Mauritania.png'},
    {countryName: 'Mauritius', countryCode: 'MUS', flag: 'Mauritius.png'},
    {countryName: 'Mayotte', countryCode: 'MYT', flag: 'France.png'},
    {countryName: 'Mexico', countryCode: 'MEX', flag: 'Mexico.png'},
    {countryName: 'Micronesia (Federated States of)	', countryCode: 'FSM', flag: 'Micronesia.png'},
    {countryName: 'Moldova (the Republic of)', countryCode: 'MDA', flag: 'Moldova.png'},
    {countryName: 'Monaco', countryCode: 'MCO', flag: 'Monaco.png'},
    {countryName: 'Mongolia', countryCode: 'MNG', flag: 'Mongolia.png'},
    {countryName: 'Montenegro', countryCode: 'MNE', flag: 'Montenegro.png'},
    {countryName: 'Montserrat', countryCode: 'MSR', flag: 'Montserrat.png'},
    {countryName: 'Morocco', countryCode: 'MAR', flag: 'Morocco.png'},
    {countryName: 'Mozambique', countryCode: 'MOZ', flag: 'Mozambique.png'},
    {countryName: 'Myanmar', countryCode: 'MMR', flag: 'MyanmarBurma.png'},
    {countryName: 'Namibia', countryCode: 'NAM', flag: 'Namibia.png'},
    {countryName: 'Nauru', countryCode: 'NRU', flag: 'Nauru.png'},
    {countryName: 'Nepal', countryCode: 'NPL', flag: 'Nepal.png'},
    {countryName: 'Netherlands ', countryCode: 'NLD', flag: 'NetherlandsAntilles.png'},
    {countryName: 'New Caledonia', countryCode: 'NCL', flag: 'NewCaledonia.png'},
    {countryName: 'New Zealand', countryCode: 'NZL', flag: 'NewZealand.png'},
    {countryName: 'Nicaragua', countryCode: 'NIC', flag: 'Nicaragua.png'},
    {countryName: 'Niger', countryCode: 'NER', flag: 'Niger.png'},
    {countryName: 'Nigeria', countryCode: 'NGA', flag: 'Nigeria.png'},
    {countryName: 'Niue', countryCode: 'NIU', flag: 'Niue.png'},
    {countryName: 'Norfolk Island', countryCode: 'NFK', flag: 'NorfolkIsland.png'},
    {countryName: 'Northern Mariana Islands', countryCode: 'MNP', flag: 'NorthernMarianaIslands.png'},
    {countryName: 'Norway', countryCode: 'NOR', flag: 'Norway.png'},
    {countryName: 'Oman', countryCode: 'OMN', flag: 'Oman.png'},
    {countryName: 'Pakistan', countryCode: 'PAK', flag: 'Pakistan.png'},
    {countryName: 'Palau', countryCode: 'PLW', flag: 'Palau.png'},
    {countryName: 'Palestine, State of', countryCode: 'PSE', flag: 'Palestine.png'},
    {countryName: 'Panama', countryCode: 'PAN', flag: 'Panama.png'},
    {countryName: 'Papua New Guinea	', countryCode: 'PNG', flag: 'PapuaNewGuinea.png'},
    {countryName: 'Paraguay	', countryCode: 'PRY', flag: 'Paraguay.png'},
    {countryName: 'Peru	', countryCode: 'PER', flag: 'Peru.png'},
    {countryName: 'Philippines ', countryCode: 'PHL', flag: 'Philippines.png'},
    {countryName: 'Pitcairn', countryCode: 'PCN', flag: 'Pitcarin.png'},
    {countryName: 'Poland', countryCode: 'POL', flag: 'Poland.png'},
    {countryName: 'Portugal', countryCode: 'PRT', flag: 'Portugal.png'},
    {countryName: 'Puerto Rico', countryCode: 'PRI', flag: 'PuertoRico.png'},
    {countryName: 'Qatar', countryCode: 'QAT', flag: 'Qatar.png'},
    {countryName: 'Republic of North Macedonia', countryCode: 'MKD', flag: 'Macedonia.png'},
    {countryName: 'Romania', countryCode: 'ROU', flag: 'Romania.png'},
    {countryName: 'Rwanda', countryCode: 'RWA', flag: 'Rwanda.png'},
    {countryName: 'Réunion', countryCode: 'REU', flag: 'Reunion.png'},
    {countryName: 'Russian Federation ', countryCode: 'RUS', flag: 'RussianFederation.png'},
    {countryName: 'Saint Lucia', countryCode: 'LCA', flag: 'SaintLucia.png'},
    {countryName: 'Samoa', countryCode: 'WSM', flag: 'Samoa.png'},
    {countryName: 'San Marino', countryCode: 'SMR', flag: 'SanMarino.png'},
    {countryName: 'Sao Tome and Principe', countryCode: 'STP', flag: 'SaoTome&Principe.png'},
    {countryName: 'Saudi Arabia', countryCode: 'SAU', flag: 'SaudiArabia.png'},
    {countryName: 'Senegal', countryCode: 'SEN', flag: 'Senegal.png'},
    {countryName: 'Serbia', countryCode: 'SRB', flag: 'SerbiaYugoslavia.png'},
    {countryName: 'Seychelles', countryCode: 'SYC', flag: 'Seychelles.png'},
    {countryName: 'Sierra Leone', countryCode: 'SLE', flag: 'SierraLeone.png'},
    {countryName: 'Singapore', countryCode: 'SGP', flag: 'Singapore.png'},
    {countryName: 'Sint Maarten', countryCode: 'SXM', flag: 'SintMaarten.png'},
    {countryName: 'Slovakia', countryCode: 'SVK', flag: 'Slovakia.png'},
    {countryName: 'Slovenia', countryCode: 'SVN', flag: 'Slovenia.png'},
    {countryName: 'Solomon Islands', countryCode: 'SLB', flag: 'SolomonIslands.png'},
    {countryName: 'Somalia', countryCode: 'SOM', flag: 'Somalia.png'},
    {countryName: 'South Africa', countryCode: 'ZAF', flag: 'SouthAfrica.png'},
    {countryName: 'South Korea (the Republic of)', countryCode: 'KOR', flag: 'SouthKorea.png'},
    {countryName: 'South Georgia and the South Sandwich Islands', countryCode: 'SGS', flag: 'SouthGeorgiaSandwichIslands.png'},
    {countryName: 'South Sudan', countryCode: 'SSD', flag: 'SouthSudan.png'},
    {countryName: 'Spain', countryCode: 'ESP', flag: 'Spain.png'},
    {countryName: 'Sri Lanka', countryCode: 'LKA', flag: 'SriLanka.png'},
    {countryName: 'Sudan', countryCode: 'SDN', flag: 'Sudan.png'},
    {countryName: 'Suriname', countryCode: 'SUR', flag: 'Suriname.png'},
    {countryName: 'Svalbard and Jan Mayen', countryCode: 'SJM', flag: 'Norway.png'},
    {countryName: 'Sweden', countryCode: 'SWE', flag: 'Sweden.png'},
    {countryName: 'Switzerland', countryCode: 'CHE', flag: 'Switzerland.png'},
    {countryName: 'Syrian Arab Republic', countryCode: 'SYR', flag: 'Syria.png'},
    {countryName: 'Taiwan (Province of China)', countryCode: 'TWN', flag: 'Taiwan.png'},
    {countryName: 'Tajikistan', countryCode: 'TJK', flag: 'Tajikistan.png'},
    {countryName: 'Tanzania, United Republic of	', countryCode: 'TZA', flag: 'Tanzania.png'},
    {countryName: 'Thailand', countryCode: 'THA', flag: 'Thailand.png'},
    {countryName: 'Timor-Leste', countryCode: 'TLS', flag: 'TimorLeste.png'},
    {countryName: 'Togo', countryCode: 'TGO', flag: 'Togo.png'},
    {countryName: 'Trinidad and Tobago', countryCode: 'TTO', flag: 'Trinidad&Tobago.png'},
    {countryName: 'Tunisia', countryCode: 'TUN', flag: 'Tunisia.png'},
    {countryName: 'Turkey', countryCode: 'TUR', flag: 'Turkey.png'},
    {countryName: 'Turkmenistan', countryCode: 'TKM', flag: 'Turkmenistan.png'},
    {countryName: 'Turks and Caicos Islands ', countryCode: 'TCA', flag: 'TurksandCaicosIslands.png'},
    {countryName: 'Tuvalu', countryCode: 'TUV', flag: 'Tuvalu.png'},
    {countryName: 'Uganda', countryCode: 'UGA', flag: 'Uganda.png'},
    {countryName: 'Ukraine', countryCode: 'UKR', flag: 'Ukraine.png'},
    {countryName: 'United Arab Emirates ', countryCode: 'ARE', flag: 'UnitedArabEmirates.png'},
    {countryName: 'United Kingdom of Great Britain and Northern Ireland ', countryCode: 'GBR', flag: 'UK.png'},
    {countryName: 'United States Minor Outlying Islands ', countryCode: 'UMI', flag: 'USA.png'},
    {countryName: 'United States of America ', countryCode: 'USA', flag: 'USA.png'},
    {countryName: 'Uruguay', countryCode: 'URY', flag: 'Uruguay.png'},
    {countryName: 'Uzbekistan', countryCode: 'UZB', flag: 'Uzbekistan.png'},
    {countryName: 'Vanuatu', countryCode: 'VUT', flag: 'Vanutau.png'},
    {countryName: 'Venezuela (Bolivarian Republic of)', countryCode: 'VEN', flag: 'Venezuela.png'},
    {countryName: 'Viet Nam	', countryCode: 'VNM', flag: 'VietNam.png'},
    {countryName: 'Virgin Islands (British)', countryCode: 'VGB', flag: 'VirginIslandsBritish.png'},
    {countryName: 'Virgin Islands (U.S.)', countryCode: 'VIR', flag: 'VirginIslandsUS.png'},
    {countryName: 'Wallis and Futuna', countryCode: 'WLF', flag: 'France.png'},
    {countryName: 'Western Sahara', countryCode: 'ESH', flag: 'WesternSahara.png'},
    {countryName: 'Yemen', countryCode: 'YEM', flag: 'Yemen.png'},
    {countryName: 'Zambia', countryCode: 'ZMB', flag: 'Zambia.png'},
    {countryName: 'Zimbabwe', countryCode: 'ZWE', flag: 'Zimbabwe.png'}
  ];
  constructor() { }
  getCountry(): CountryModel[] {
    return this.country.sort((a, b) => a.countryName.localeCompare(b.countryName));;
  }
}
