import { Injectable } from '@angular/core';
import {CurrencyModel} from '../models/currency.model';

@Injectable({
  providedIn: 'root'
})
export class CurrencyService {
  cur: CurrencyModel[] = [
    {currencyName: 'Albania Lek', currencyCode: 'ALL', currencySymbol: 'Lek', flag: 'Albania.png'},
    {currencyName: 'Afghanistan Afghani', currencyCode: 'AFN', currencySymbol: '؋', flag: 'Afghanistan.png'},
    {currencyName: 'Argentina Peso', currencyCode: 'ARS', currencySymbol: '$', flag: 'Argentina.png'},
    {currencyName: 'Aruba Guilder', currencyCode: 'AWG', currencySymbol: 'ƒ', flag: 'Aruba.png'},
    {currencyName: 'Australia Dollar', currencyCode: 'AUD', currencySymbol: '$', flag: 'Australia.png'},
    {currencyName: 'Azerbaijan Manat', currencyCode: 'AZN', currencySymbol: '₼', flag: 'Azerbaijan.png'},
    {currencyName: 'Bahamas Dollar', currencyCode: 'BSD', currencySymbol: '$', flag: 'Bahamas.png'},
    {currencyName: 'Barbados Dollar', currencyCode: 'BBD', currencySymbol: '$', flag: 'Barbados.png'},
    {currencyName: 'Belarus Ruble', currencyCode: 'BYN', currencySymbol: 'Br', flag: 'Belarus.png'},
    {currencyName: 'Belize Dollar', currencyCode: 'BZD', currencySymbol: 'BZ$', flag: 'Belize.png'},
    {currencyName: 'Bermuda Dollar', currencyCode: 'BMD', currencySymbol: '$', flag: 'Bermuda.png'},
    {currencyName: 'Bolivia Bolíviano', currencyCode: 'BOB', currencySymbol: '$b', flag: 'Bolivia.png'},
    {currencyName: 'Bosnia and Herzegovina Convertible Mark', currencyCode: 'BAM', currencySymbol: 'KM	', flag: 'Bosnia & Herzegovina.png'},
    {currencyName: 'Botswana Pula', currencyCode: 'BWP', currencySymbol: 'P', flag: 'Botswana.png'},
    {currencyName: 'Bulgaria Lev', currencyCode: 'BGN', currencySymbol: 'лв', flag: 'Bulgaria.png'},
    {currencyName: 'Brazil Real', currencyCode: 'BRL', currencySymbol: 'R$', flag: 'Brazil.png'},
    {currencyName: 'Brunei Darussalam Dollar', currencyCode: 'BND', currencySymbol: '$', flag: 'Brunei.png'},
    {currencyName: 'Cambodia Riel', currencyCode: 'KHR', currencySymbol: '៛', flag: 'Cambodja.png'},
    {currencyName: 'Canada Dollar', currencyCode: 'CAD', currencySymbol: '$', flag: 'Canada.png'},
    {currencyName: 'Cayman Islands Dollar', currencyCode: 'KYD', currencySymbol: '$', flag: 'Cayman Islands.png'},
    {currencyName: 'Chile Peso', currencyCode: 'CLP', currencySymbol: '$', flag: 'Chile.png'},
    {currencyName: 'China Yuan Renminbi', currencyCode: 'CNY', currencySymbol: '¥', flag: 'China.png'},
    {currencyName: 'Colombia Peso', currencyCode: 'COP', currencySymbol: '$', flag: 'Colombia.png'},
    {currencyName: 'Costa Rica Colon', currencyCode: 'CRC', currencySymbol: '₡', flag: 'Costa Rica.png'},
    {currencyName: 'Croatia Kuna', currencyCode: 'HRK', currencySymbol: 'kn', flag: 'Croatia.png'},
    {currencyName: 'Cuba Peso', currencyCode: 'CUP', currencySymbol: '₱', flag: 'Cuba.png'},
    {currencyName: 'Czech Republic Koruna', currencyCode: 'CZK', currencySymbol: 'Kč', flag: 'Czech Republic.png'},
    {currencyName: 'Denmark Krone', currencyCode: 'DKK', currencySymbol: 'kr', flag: 'Denmark.png'},
    {currencyName: 'Dominican Republic Peso', currencyCode: 'DOP', currencySymbol: 'RD$', flag: 'Dominica.png'},
    {currencyName: 'East Caribbean Dollar', currencyCode: 'XCD', currencySymbol: '$', flag: 'Dominica.png'},
    {currencyName: 'Egypt Pound', currencyCode: 'EGP', currencySymbol: '£', flag: 'Egypt.png'},
    {currencyName: 'El Salvador Colon', currencyCode: 'SVC', currencySymbol: '$', flag: 'El Salvador.png'},
    {currencyName: 'Euro Member Countrie', currencyCode: 'EUR', currencySymbol: '€', flag: 'European Union.png'},
    {currencyName: 'Falkland Islands (Malvinas) Pound', currencyCode: 'FKP', currencySymbol: '£', flag: 'European Union.png'},
    {currencyName: 'Fiji Dollar', currencyCode: 'FJD', currencySymbol: '$', flag: 'Fiji.png'},
    {currencyName: 'Ghana Cedi', currencyCode: 'GHS', currencySymbol: '¢', flag: 'Ghana.png'},
    {currencyName: 'Gibraltar Pound', currencyCode: 'GIP', currencySymbol: '£', flag: 'Gibraltar.png'},
    {currencyName: 'Guatemala Quetzal', currencyCode: 'GTQ', currencySymbol: 'Q', flag: 'Guatemala.png'},
    {currencyName: 'Guernsey Pound', currencyCode: 'GGP', currencySymbol: '£', flag: 'Guernsey.png'},
    {currencyName: 'Guyana Dollar', currencyCode: 'GYD', currencySymbol: '$', flag: 'Guyana.png'},
    {currencyName: 'Honduras Lempira', currencyCode: 'HNL', currencySymbol: 'L', flag: 'Honduras.png'},
    {currencyName: 'Hong Kong Dollar', currencyCode: 'HKD', currencySymbol: '$', flag: 'Hong Kong.pngk'},
    {currencyName: 'Hungary Forint', currencyCode: 'HUF', currencySymbol: 'Ft', flag: 'Hungary.png'},
    {currencyName: 'Iceland Krona', currencyCode: 'ISK', currencySymbol: 'kr', flag: 'Iceland.png'},
    {currencyName: 'India Rupee', currencyCode: 'INR', currencySymbol: 'kr', flag: 'Iceland.png'},
    {currencyName: 'Indonesia Rupiah', currencyCode: 'IDR', currencySymbol: 'Rp', flag: 'Indonezia.png'},
    {currencyName: 'Iran Rial', currencyCode: 'IRR', currencySymbol: '﷼', flag: 'Iran.png'},
    {currencyName: 'Isle of Man Pound', currencyCode: 'IMP', currencySymbol: '£', flag: 'Isle of Man.png'},
    {currencyName: 'Israel Shekel', currencyCode: 'ILS', currencySymbol: '₪	', flag: 'Isle of Man.png'},
    {currencyName: 'Jamaica Dollar', currencyCode: 'JMD', currencySymbol: 'J$', flag: 'Jamaica.png'},
    {currencyName: 'Japan Yen', currencyCode: 'JPY', currencySymbol: '¥', flag: 'Japan.png'},
    {currencyName: 'Jersey Pound', currencyCode: 'JEP', currencySymbol: '£', flag: 'Jersey.png'},
    {currencyName: 'Kazakhstan Tenge', currencyCode: 'KZT', currencySymbol: 'лв', flag: 'Kazakhstan.png'},
    {currencyName: 'Korea (North) Won', currencyCode: 'KPW', currencySymbol: '₩', flag: 'Kazakhstan.png'},
    {currencyName: 'Kyrgyzstan Som', currencyCode: 'KGS', currencySymbol: 'лв', flag: 'Kyrgyzstan.png'},
    {currencyName: 'Laos Kip', currencyCode: 'LAK', currencySymbol: '₭', flag: 'Laos.png'},
    {currencyName: 'Lebanon Pound', currencyCode: 'LBP', currencySymbol: '£', flag: 'Lebanon.png'},
    {currencyName: 'Liberia Dollar', currencyCode: 'LRD', currencySymbol: '$', flag: 'Liberia.png'},
    {currencyName: 'Macedonia Denar', currencyCode: 'MKD', currencySymbol: 'ден', flag: 'Macedonia.png'},
    {currencyName: 'Malaysia Ringgit', currencyCode: 'MYR', currencySymbol: 'RM', flag: 'Malaysia.png'},
    {currencyName: 'Mauritius Rupee', currencyCode: 'MUR', currencySymbol: '₨', flag: 'Mauritius.png'},
    {currencyName: 'Mexico Peso', currencyCode: 'MXN', currencySymbol: '$', flag: 'Mexico.png'},
    {currencyName: 'Mongolia Tughrik', currencyCode: 'MNT', currencySymbol: '₮', flag: 'Mongolia.png'},
    {currencyName: 'Mozambique Metical', currencyCode: 'MZN', currencySymbol: 'MT', flag: 'Mozambique.png'},
    {currencyName: 'Namibia Dollar', currencyCode: 'NAD', currencySymbol: '$', flag: 'Namibia.png'},
    {currencyName: 'Nepal Rupee', currencyCode: 'NPR', currencySymbol: '₨', flag: 'Nepal.png'},
    {currencyName: 'Netherlands Antilles Guilder', currencyCode: 'ANG', currencySymbol: 'ƒ', flag: 'Netherlands Antilles.png'},
    {currencyName: 'New Zealand Dollar', currencyCode: 'NZD', currencySymbol: '$', flag: 'New Zealand.png'},
    {currencyName: 'Nicaragua Cordoba', currencyCode: 'NIO', currencySymbol: 'C$', flag: 'Nicaragua.png'},
    {currencyName: 'Nigeria Naira', currencyCode: 'NGN', currencySymbol: '₦', flag: 'Nigeria.png'},
    {currencyName: 'Norway Krone', currencyCode: 'NOK', currencySymbol: 'kr', flag: 'Norway.png'},
    {currencyName: 'Oman Rial', currencyCode: 'OMR', currencySymbol: '﷼', flag: 'Oman.png'},
    {currencyName: 'Pakistan Rupee', currencyCode: 'PKR', currencySymbol: '₨', flag: 'Pakistan.png'},
    {currencyName: 'Panama Balboa', currencyCode: 'PAB', currencySymbol: 'B/.', flag: 'Panama.png'},
    {currencyName: 'Paraguay Guarani', currencyCode: 'PYG', currencySymbol: 'Gs', flag: 'Paraguay.png'},
    {currencyName: 'Peru Sol', currencyCode: 'PEN', currencySymbol: 'S/.', flag: 'Peru.png'},
    {currencyName: 'Philippines Peso', currencyCode: 'PHP', currencySymbol: '₱', flag: 'Philippines.png'},
    {currencyName: 'Poland Zloty', currencyCode: 'PLN', currencySymbol: 'zł', flag: 'Poland.png'},
    {currencyName: 'Qatar Riyal', currencyCode: 'QAR', currencySymbol: '﷼', flag: 'Qatar.png'},
    {currencyName: 'Romania Leu', currencyCode: 'RON', currencySymbol: 'lei', flag: 'Romania.png'},
    {currencyName: 'Russia Ruble', currencyCode: 'RUB', currencySymbol: '₽', flag: 'Russian Federation.png'},
    {currencyName: 'Saint Helena Pound', currencyCode: 'SHP', currencySymbol: '£', flag: 'Saint Lucia.png'},
    {currencyName: 'Saudi Arabia Riyal', currencyCode: 'SAR', currencySymbol: '﷼', flag: 'Saudi Arabia.png'},
    {currencyName: 'Serbia Dinar', currencyCode: 'RSD', currencySymbol: 'Дин.', flag: 'Serbia(Yugoslavia).png'},
    {currencyName: 'Seychelles Rupee', currencyCode: 'SCR', currencySymbol: '₨', flag: 'Seychelles.png'},
    {currencyName: 'Singapore Dollar', currencyCode: 'SGD', currencySymbol: '$', flag: 'Singapore.png'},
    {currencyName: 'Solomon Islands Dollar', currencyCode: 'SBD', currencySymbol: '$', flag: 'Solomon Islands.png'},
    {currencyName: 'Somalia Shilling', currencyCode: 'SOS', currencySymbol: 'S', flag: 'Somalia.png'},
    {currencyName: 'South Africa Rand', currencyCode: 'ZAR', currencySymbol: 'R', flag: 'South Africa.png'},
    {currencyName: 'Sri Lanka Rupee', currencyCode: 'LKR', currencySymbol: '₨', flag: 'Sri Lanka.png'},
    {currencyName: 'Sweden Krona', currencyCode: 'SEK', currencySymbol: 'kr', flag: 'Sweden.png'},
    {currencyName: 'Switzerland Franc', currencyCode: 'CHF', currencySymbol: 'CHF', flag: 'Swaziland.png'},
    {currencyName: 'Suriname Dollar', currencyCode: 'SRD', currencySymbol: '$', flag: 'Suriname.png'},
    {currencyName: 'Syria Pound', currencyCode: 'SYP', currencySymbol: '£', flag: 'Syria.png'},
    {currencyName: 'Taiwan New Dollar', currencyCode: 'TWD', currencySymbol: 'NT$', flag: 'Taiwan.png'},
    {currencyName: 'Thailand Baht', currencyCode: 'THB', currencySymbol: '฿', flag: 'Thailand.png'},
    {currencyName: 'Trinidad and Tobago Dollar', currencyCode: 'TTD', currencySymbol: 'TT$', flag: 'Trinidad & Tobago.png'},
    {currencyName: 'Turkey Lira', currencyCode: 'TRY', currencySymbol: 'TT$', flag: 'Turkey.png'},
    {currencyName: 'Tuvalu Dollar', currencyCode: 'TVD', currencySymbol: '$', flag: 'Tuvalu.png'},
    {currencyName: 'Ukraine Hryvnia', currencyCode: 'UAH', currencySymbol: '₴', flag: 'Ukraine.png'},
    {currencyName: 'United Kingdom Pound', currencyCode: 'GBP', currencySymbol: '£', flag: 'UK.png'},
    {currencyName: 'United States Dollar', currencyCode: 'USD', currencySymbol: '$', flag: 'USA.png'},
    {currencyName: 'Uruguay Peso', currencyCode: 'UYU', currencySymbol: '$U	', flag: 'Uruguay.png'},
    {currencyName: 'Uzbekistan Som', currencyCode: 'UZS', currencySymbol: 'лв', flag: 'Uzbekistan.png'},
    {currencyName: 'Venezuela Bolívar', currencyCode: 'VEF', currencySymbol: 'Bs', flag: 'Venezuela.png'},
    {currencyName: 'Viet Nam Dong', currencyCode: 'VND', currencySymbol: '₫', flag: 'Viet Nam.png'},
    {currencyName: 'Yemen Rial', currencyCode: 'YER', currencySymbol: '﷼', flag: 'Yemen.png'},
    {currencyName: 'Zimbabwe Dollar', currencyCode: 'ZWD', currencySymbol: 'Z$', flag: 'Zimbabwe.png'}
  ];
  constructor() { }

  getCurrency(): CurrencyModel[] {
    return this.cur;
  }
}
